name: EpicGamesFreeGamesUpdate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_NAME: ${{ secrets.APP_NAME }}
  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
  EPIC_GAMES_PASSWORD: ${{ secrets.EPIC_GAMES_PASSWORD }}
  GIT_HASH: master
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  TOTP_MFA: ${{ secrets.TOTP_MFA }}

jobs:
  update_app:
    name: Update EpicGamesFreeGames app on Heroku.
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: stable
        # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: curl https://cli-assets.heroku.com/install.sh | sh
    - run: sudo apt-get update && sudo apt-get install jq openssl redis -y
    - run: bash deploy_update_app.sh -a $APP_NAME -g $GIT_HASH -t update